export const API = 'http://localhost:3000'

export const EXCEL_IMPORT = {
	EXCEL_IMPORT_REQUEST: 'EXCEL_IMPORT_REQUEST',
	EXCEL_IMPORT_SUCCESS: 'EXCEL_IMPORT_SUCCESS',
	EXCEL_IMPORT_FAILED:  'EXCEL_IMPORT_FAILED'
}

export const EXCEL_PROCESS = {
	EXCEL_PROCESS_REQUEST: 'EXCEL_PROCESS_REQUEST',
	EXCEL_PROCESS_SUCCESS: 'EXCEL_PROCESS_SUCCESS',
	EXCEL_PROCESS_FAILED:  'EXCEL_PROCESS_FAILED'
}

export const EXCEL_PROCESS_DATA = {
	EXCEL_PROCESS_DATA_REQUEST: 'EXCEL_PROCESS_DATA_REQUEST',
	EXCEL_PROCESS_DATA_SUCCESS: 'EXCEL_PROCESS_DATA_SUCCESS',
	EXCEL_PROCESS_DATA_FAILED:  'EXCEL_PROCESS_DATA_FAILED'
}